### ISSUE TITLE
Allowing more parents leads to worse score

### ISSUE THREAD

**Issue by afbarnard** [tdbn/tDBN#1]
I was just trying out your software on some synthetic data and encountered a non-intuitive result. It looks like allowing more parents results in a worse score. I used the log-likelihood score, but the output is positive, so I assume the reported score is actually negative log-likelihood. Thus I expect a better score to be smaller. However, increasing the parents from 2 to 3 leads to a higher (worse) score. Is my interpretation of the score wrong or is allowing more parents actually leading to a worse log-likelihood?

Run with 2 parents:

```
$ java8 -jar tDBN-0.1.3.jar --markovLag 1 --numParents 2 --scoringFunction LL --inputFile synth.csv
Evaluating network with LL score.
Number of networks with max score: 1
Finding a maximum branching.
Network score: 9.996015997539871
```

Run with 3 parents:

```
$ java8 -jar tDBN-0.1.3.jar --markovLag 1 --numParents 3 --scoringFunction LL --inputFile synth.csv
Evaluating network with LL score.
Number of networks with max score: 1
Finding a maximum branching.
Network score: 13.173599450929487
```

**Comment by josemonteiro** [comment]
Hi, thanks for taking interest in the software and reporting this issue!

The result you're getting is not intuitive, because what is being reported as "network score" is not the log-likelihood of the network. This software is the implementation of an algorithm [1] that involves finding a maximum branching to obtain the optimal DBN. This maximum branching is found within a complete directed graph, where edges are weighted according to Eq. (10) in the referred paper. The network score that is being erroneously reported is the sum of the weights of the branching's directed edges.

I will update the software within the next hours to make it print the correct network score.

[1] Monteiro, J. L., Vinga, S., & Carvalho, A. M. (2015, July). Polynomial-time algorithm for learning optimal tree-augmented dynamic Bayesian networks. In Uncertainty in Artificial Intelligence (Vol. 31, pp. 622-631). http://auai.org/uai2015/proceedings/papers/329.pdf

**Comment by josemonteiro** [comment]
New release with correct network score printing: https://github.com/josemonteiro/tDBN/releases/tag/0.1.4

I will later update the project website.

Please let me know if you get the expected results with this one.
